--1
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR(10),
    USE_YN CHAR(1) 
    );

--2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
    );
  
--3
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_NAME PRIMARY KEY(NAME);

--4
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME CONSTRAINT NAME_NN NOT NULL;

   
--5
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR(10);

--6
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

--7
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT PK_NAME TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C0011212 TO PK_CLASS_TYPE;

--8
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;

--9
TB_PARTMENT FOREI


--10
CREATE VIEW VW_학생일반정보 
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름 , STUDENT_ADDRESS 학생주소
FROM TB_STUDENT;

DROP VIEW VW_학생일반정보;
SELECT * FROM VW_학생일반정보;

GRANT CREATE VIEW TO WORKBOOK;

--11
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME 학생이름 , DEPARTMENT_NAME 학과이름 , PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S , TB_DEPARTMENT D , TB_PROFESSOR F
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
  AND F.PROFESSOR_NO = S.COACH_PROFESSOR_NO;


SELECT * FROM  VW_지도면담;


