-- 1.
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 1 ASC;

--2.
SELECT STUDENT_NAME,  STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME 학생이름, TO_CHAR(ENTRANCE_DATE, 'YYMMDD') 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE,1,2) >=90
ORDER BY 1 ASC;

-- 4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ASC;

-- 5.
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = 200402 AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

-- 6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT A, TB_DEPARTMENT B
WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO
ORDER BY STUDENT_NAME;

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;
--7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS A , TB_DEPARTMENT B
WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO
ORDER BY DEPARTMENT_NAME;

--8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM  TB_CLASS A , TB_PROFESSOR B
WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO
GROUP BY CLASS_NAME, PROFESSOR_NAME
ORDER BY PROFESSOR_NAME;

-- 8-2
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
ORDER BY TB_CLASS.DEPARTMENT_NO , 1 , 2 ASC ;

--9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR P  USING(PROFESSOR_NO)
WHERE P.DEPARTMENT_NO IN (
    SELECT DEPARTMENT_NO
    FROM TB_DEPARTMENT
    WHERE CATEGORY = '인문사회'
)
--JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)
--WHERE D.CATEGORY = '인문사회'
ORDER BY TB_CLASS.DEPARTMENT_NO , 2 ASC ;

--18
SELECT STUDENT_NO, STUDENT_NAME
FROM (
SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) AS POINT
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = ( 
                        SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '국어국문학과'
                      )
GROUP BY STUDENT_NO , STUDENT_NAME
ORDER BY POINT DESC
)
WHERE ROWNUM = 1;

-- 18.2

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = ( 
                        SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '국어국문학과'
                      )
GROUP BY STUDENT_NO , STUDENT_NAME
HAVING AVG(POINT) = (
                        SELECT MAX(POINT)
                        FROM TB_STUDENT
                        JOIN TB_GRADE USING(STUDENT_NO)
                        WHERE DEPARTMENT_NO = '001'
                        GROUP BY STUDENT_NO
                    );













